version: "3.9"  # optional since v1.27.0
services:
  santex-football-data-api:
    build: .
    ports:
      - "8081:8080"
    volumes:
      - ".:/usr/src"
    links:
      - santex-football-data-database 
      - santex-football-data-mongo 

  santex-football-data-database:
    image: mysql:8.0.29
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example

  santex-football-data-mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: santex-football-data-database
      
  santex-football-data-mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@santex-football-data-mongo:27017/
# volumes:
#   logvolume01: {}