version: "3.9"  # optional since v1.27.0
services:
  football-data-api:
    build: .
    ports:
      - "8081:8080"
    volumes:
      - "./app:/usr/src/app"
    links:
      - football-data-database      
  football-data-database:
    image: mysql:8.0.29
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
# volumes:
#   logvolume01: {}